# Macro file for the initialization of example B2 
# in interactive session
#
# Set some default verbose
/control/verbose 2
/control/saveHistory
/run/verbose 2
#
# Change the default number of threads (in multi-threaded mode)
/run/numberOfThreads 1
#
# Number of events displayed
/vis/multithreading/maxEventQueueSize 100000
#
# Set Seed
/random/setSeeds 8904139 1546570
#
#
# Initialize kernel
/run/initialize
#
# Visualization setting
/control/execute vis.mac
